apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-selfsigned-ca
spec:
  isCA: true
  commonName: my-selfsigned-ca
  secretName: root-secret2
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: ns-level2-dev-something-clusterissuer
    kind: ClusterIssuer
    group: cert-manager.io